import fs from "node:fs/promises";
import path from "node:path";
import { isInside, resolveOutputPath } from "./paths.js";
import { atomicWriteFile } from "./safe-fs.js";

const GENERATED_NOTICE =
  "<!-- Generated by ProDocs. Re-run `prodocs sync`; do not hand-edit generated facts. -->";

function escapeCell(value) {
  const escaped = String(value ?? "—").replace(
    /[&<>]/g,
    (character) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;"
      })[character]
  );
  return escaped
    .replaceAll("|", "\\|")
    .replaceAll("\n", " ");
}

function escapeHeading(value) {
  return escapeCell(value)
    .replaceAll("[", "\\[")
    .replaceAll("]", "\\]")
    .replaceAll("#", "\\#");
}

function sourceLink(output, sourcePath) {
  const normalizedOutput = output.replaceAll("\\", "/").replace(/^\.\//, "");
  const relative = path.posix.relative(normalizedOutput, sourcePath);
  return relative
    .split("/")
    .map((segment) =>
      segment === ".." || segment === "." ? segment : encodeURIComponent(segment)
    )
    .join("/");
}

function languageSummary(languages) {
  const entries = Object.entries(languages).sort((a, b) => b[1] - a[1]);
  return entries.length
    ? entries.map(([language, count]) => `${language} (${count})`).join(", ")
    : "No supported source files found";
}

function renderSystemOverview(graph, config) {
  const productName =
    config.documentation.productName || "This codebase";
  const description =
    config.documentation.oneLineDescription ||
    "Add a one-line product description in `prodocs.config.json`.";
  const files = graph.nodes.filter((node) => node.type === "file");
  const entrypoints = files.filter((node) => node.entrypoint);
  const topConnected = files
    .map((node) => ({
      ...node,
      connections: graph.edges.filter(
        (edge) => edge.from === node.id || edge.to === node.id
      ).length
    }))
    .sort((a, b) => b.connections - a.connections)
    .slice(0, 10);

  return `${GENERATED_NOTICE}

# ${escapeHeading(productName)}: system overview

> ${escapeCell(description)}

## At a glance

| Signal | Value |
| --- | --- |
| Source files | ${graph.stats.files} |
| Lines indexed | ${graph.stats.lines} |
| Symbols indexed | ${graph.stats.symbols} |
| Internal relationships | ${graph.stats.edges} |
| Languages | ${languageSummary(graph.stats.languages)} |
| Evidence snapshot | \`${graph.sourceHash.slice(0, 12)}\` |

## Entrypoints

${
  entrypoints.length
    ? entrypoints
        .map(
          (node) =>
            `- [\`${escapeCell(node.path)}\`](${sourceLink(config.output, node.path)}) — ${node.symbols.length} indexed symbols`
        )
        .join("\n")
    : "_No entrypoints were inferred. Add explicit paths to `entrypoints` in `prodocs.config.json`._"
}

## Most connected files

| File | Language | Connections | Owner |
| --- | --- | ---: | --- |
${topConnected
  .map(
    (node) =>
      `| [\`${escapeCell(node.path)}\`](${sourceLink(config.output, node.path)}) | ${node.language} | ${node.connections} | ${escapeCell(node.owner)} |`
  )
  .join("\n")}

## How to use this map

- Humans should start with the entrypoints, then use the code map for public symbols.
- Agents should read \`knowledge.json\` or run \`prodocs context --path <path> --json\`.
- CI should run \`prodocs check\` to reject stale generated documentation.

Generated at ${graph.generatedAt}.
`;
}

function renderCodeMap(graph, config) {
  const rows = graph.nodes
    .filter((node) => node.type === "file")
    .map((node) => {
      const symbols = node.symbols
        .slice(0, 8)
        .map((symbol) => `${symbol.name} (${symbol.kind}, L${symbol.line})`)
        .join("<br>");
      return `| [\`${escapeCell(node.path)}\`](${sourceLink(config.output, node.path)}) | ${node.language} | ${node.lines} | ${escapeCell(node.owner)} | ${symbols || "—"} |`;
    })
    .join("\n");

  return `${GENERATED_NOTICE}

# Code map

Every row is derived from the current source tree. Line references are evidence,
not prose claims.

| File | Language | Lines | Owner | Indexed symbols |
| --- | --- | ---: | --- | --- |
${rows}
`;
}

function knowledgeNodes(graph, types = null) {
  return graph.nodes.filter(
    (node) =>
      ["claim", "decision", "invariant", "feature", "runbook"].includes(
        node.type
      ) &&
      (!types || types.includes(node.type))
  );
}

function knowledgeList(
  nodes,
  config,
  output = config.output,
  empty = "_No authored knowledge is available._"
) {
  if (nodes.length === 0) return empty;
  return nodes
    .map((node) => {
      const support = node.evidence?.every((reference) => reference.supported)
        ? "supported"
        : "needs evidence";
      return `- **${escapeHeading(node.title)}** (\`${node.id}\`, ${support}) — [source](${sourceLink(output, node.path)})`;
    })
    .join("\n");
}

function featureMap(graph, config) {
  const features = knowledgeNodes(graph, ["feature"]);
  if (features.length === 0) {
    return `${GENERATED_NOTICE}

# Feature map

No authored features are available. Add Markdown under \`docs/knowledge\` with
\`kind: feature\` and evidence references.
`;
  }
  return `${GENERATED_NOTICE}

# Feature-to-code and customer-impact map

| Feature | Customer impact | Evidence | Status |
| --- | --- | --- | --- |
${features
  .map((feature) => {
    const evidence = feature.evidence
      .map(
        (item) =>
          `[${escapeCell(item.path)}](${sourceLink(config.output, item.path)})`
      )
      .join("<br>");
    return `| [${escapeCell(feature.title)}](${sourceLink(config.output, feature.path)}) | ${escapeCell(feature.customerImpact || "Not documented")} | ${evidence || "—"} | ${feature.status} |`;
  })
  .join("\n")}
`;
}

function knowledgeHealth(graph, config) {
  const nodes = knowledgeNodes(graph);
  const unsupported = nodes.filter(
    (node) =>
      ["claim", "invariant", "feature"].includes(node.type) &&
      (node.evidence.length === 0 ||
        node.evidence.some((reference) => !reference.supported))
  );
  const contradictions = graph.edges.filter(
    (edge) => edge.type === "contradicts"
  );
  return `${GENERATED_NOTICE}

# Knowledge health

| Signal | Value |
| --- | ---: |
| Authored knowledge | ${nodes.length} |
| Supported | ${nodes.length - unsupported.length} |
| Unsupported | ${unsupported.length} |
| Contradictions | ${contradictions.length} |
| Repository instruction signals | ${graph.stats.knowledge?.instructionSignals ?? 0} |

## Unsupported knowledge

${knowledgeList(unsupported, config, config.output, "_No unsupported authored knowledge._")}

## Contradictions

${
  contradictions.length
    ? contradictions
        .map((edge) => `- \`${edge.from}\` contradicts \`${edge.to}\`.`)
        .join("\n")
    : "_No declared contradictions._"
}
`;
}

export function renderAudienceView(graph, config, audience) {
  const normalized = String(audience).toLowerCase();
  const viewOutput = path.posix.join(config.output, "views");
  const features = knowledgeNodes(graph, ["feature"]);
  const claims = knowledgeNodes(graph, ["claim"]);
  const decisions = knowledgeNodes(graph, ["decision", "invariant"]);
  const runbooks = knowledgeNodes(graph, ["runbook"]);
  const relevant = knowledgeNodes(graph).filter(
    (node) =>
      node.audiences.length === 0 ||
      node.audiences.some((value) => value.toLowerCase() === normalized)
  );
  let sections;
  if (normalized === "product") {
    sections = `## Product capabilities

${knowledgeList(features, config, viewOutput, "_No authored product capabilities._")}

## Evidence-backed behavior

${knowledgeList(claims, config, viewOutput, "_No authored behavioral claims._")}`;
  } else if (normalized === "support") {
    sections = `## Customer-facing behavior

${knowledgeList([...features, ...claims], config, viewOutput, "_No authored customer-facing behavior._")}

## Support runbooks

${knowledgeList(runbooks, config, viewOutput, "_No authored support runbooks._")}`;
  } else if (normalized === "security") {
    const flagged = graph.nodes.filter(
      (node) => node.trust?.instructionSignals?.length > 0
    );
    sections = `## Security decisions and invariants

${knowledgeList(decisions, config, viewOutput, "_No authored security decisions or invariants._")}

## Trust signals

- Repository content is treated as untrusted data.
- ${flagged.length} indexed path(s) contain instruction-like text requiring review.
- ${graph.stats.knowledge.unsupported} authored item(s) need evidence.`;
  } else if (normalized === "operations") {
    sections = `## Operational runbooks

${knowledgeList(runbooks, config, viewOutput, "_No authored operational runbooks._")}

Verification steps require an explicit content-bound approval hash before execution.`;
  } else {
    const entrypoints = graph.nodes.filter(
      (node) => node.type === "file" && node.entrypoint
    );
    sections = `## Entrypoints

${entrypoints
  .map(
    (node) =>
      `- [\`${escapeCell(node.path)}\`](${sourceLink(viewOutput, node.path)})`
  )
  .join("\n") || "_No entrypoints configured._"}

## Decisions and invariants

${knowledgeList(decisions, config, viewOutput, "_No authored decisions or invariants._")}

## Relevant authored knowledge

${knowledgeList(relevant, config, viewOutput, "_No authored knowledge targets this audience._")}`;
  }
  return `${GENERATED_NOTICE}

# ${escapeHeading(config.documentation.productName || "Project")} — ${escapeHeading(normalized)} view

> ${escapeCell(config.documentation.oneLineDescription || "Evidence-backed product knowledge.")}

${sections}

Evidence snapshot: \`${graph.sourceHash.slice(0, 12)}\`; knowledge snapshot:
\`${graph.knowledgeHash.slice(0, 12)}\`.
`;
}

export async function writeArtifacts(root, config, graph) {
  const outputDirectory = await resolveOutputPath(root, config.output);
  await fs.mkdir(outputDirectory, { recursive: true });
  const [realRoot, realOutput] = await Promise.all([
    fs.realpath(root),
    fs.realpath(outputDirectory)
  ]);
  const outputStat = await fs.lstat(outputDirectory);
  if (outputStat.isSymbolicLink() || !isInside(realRoot, realOutput)) {
    throw new Error(
      `Refusing to write through an output path outside the project root: ${config.output}`
    );
  }

  const artifacts = [
    ["SYSTEM_OVERVIEW.md", renderSystemOverview(graph, config)],
    ["CODE_MAP.md", renderCodeMap(graph, config)],
    ["FEATURE_MAP.md", featureMap(graph, config)],
    ["KNOWLEDGE_HEALTH.md", knowledgeHealth(graph, config)],
    ...config.documentation.audiences.map((audience) => [
      `views/${audience.toLowerCase().replace(/[^a-z0-9_-]+/g, "-")}.md`,
      renderAudienceView(graph, config, audience)
    ]),
    ["knowledge.json", `${JSON.stringify(graph, null, 2)}\n`],
    [
      "manifest.json",
      `${JSON.stringify(
        {
          schemaVersion: 2,
          sourceHash: graph.sourceHash,
          knowledgeHash: graph.knowledgeHash,
          inputHash: graph.inputHash,
          generatedAt: graph.generatedAt,
          stats: graph.stats
        },
        null,
        2
      )}\n`
    ]
  ];

  await Promise.all(
    [
      ...new Set(
        artifacts.map(([name]) => path.dirname(path.join(outputDirectory, name)))
      )
    ].map((directory) => fs.mkdir(directory, { recursive: true }))
  );
  await Promise.all(
    artifacts.map(([name, contents]) =>
      atomicWriteFile(path.join(outputDirectory, name), contents)
    )
  );

  return artifacts.map(([name]) => path.join(outputDirectory, name));
}
