import fs from "node:fs/promises";
import path from "node:path";
import { isInside, resolveOutputPath } from "./paths.js";
import { atomicWriteFile } from "./safe-fs.js";

const GENERATED_NOTICE =
  "<!-- Generated by ProDocs. Re-run `prodocs sync`; do not hand-edit generated facts. -->";

function escapeCell(value) {
  const escaped = String(value ?? "—").replace(
    /[&<>]/g,
    (character) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;"
      })[character]
  );
  return escaped
    .replaceAll("|", "\\|")
    .replaceAll("\n", " ");
}

function escapeHeading(value) {
  return escapeCell(value)
    .replaceAll("[", "\\[")
    .replaceAll("]", "\\]")
    .replaceAll("#", "\\#");
}

function sourceLink(output, sourcePath) {
  const normalizedOutput = output.replaceAll("\\", "/").replace(/^\.\//, "");
  const relative = path.posix.relative(normalizedOutput, sourcePath);
  return relative
    .split("/")
    .map((segment) =>
      segment === ".." || segment === "." ? segment : encodeURIComponent(segment)
    )
    .join("/");
}

function languageSummary(languages) {
  const entries = Object.entries(languages).sort((a, b) => b[1] - a[1]);
  return entries.length
    ? entries.map(([language, count]) => `${language} (${count})`).join(", ")
    : "No supported source files found";
}

function renderSystemOverview(graph, config) {
  const productName =
    config.documentation.productName || "This codebase";
  const description =
    config.documentation.oneLineDescription ||
    "Add a one-line product description in `prodocs.config.json`.";
  const entrypoints = graph.nodes.filter((node) => node.entrypoint);
  const topConnected = graph.nodes
    .map((node) => ({
      ...node,
      connections: graph.edges.filter(
        (edge) => edge.from === node.id || edge.to === node.id
      ).length
    }))
    .sort((a, b) => b.connections - a.connections)
    .slice(0, 10);

  return `${GENERATED_NOTICE}

# ${escapeHeading(productName)}: system overview

> ${escapeCell(description)}

## At a glance

| Signal | Value |
| --- | --- |
| Source files | ${graph.stats.files} |
| Lines indexed | ${graph.stats.lines} |
| Symbols indexed | ${graph.stats.symbols} |
| Internal relationships | ${graph.stats.edges} |
| Languages | ${languageSummary(graph.stats.languages)} |
| Evidence snapshot | \`${graph.sourceHash.slice(0, 12)}\` |

## Entrypoints

${
  entrypoints.length
    ? entrypoints
        .map(
          (node) =>
            `- [\`${escapeCell(node.path)}\`](${sourceLink(config.output, node.path)}) — ${node.symbols.length} indexed symbols`
        )
        .join("\n")
    : "_No entrypoints were inferred. Add explicit paths to `entrypoints` in `prodocs.config.json`._"
}

## Most connected files

| File | Language | Connections | Owner |
| --- | --- | ---: | --- |
${topConnected
  .map(
    (node) =>
      `| [\`${escapeCell(node.path)}\`](${sourceLink(config.output, node.path)}) | ${node.language} | ${node.connections} | ${escapeCell(node.owner)} |`
  )
  .join("\n")}

## How to use this map

- Humans should start with the entrypoints, then use the code map for public symbols.
- Agents should read \`knowledge.json\` or run \`prodocs context --path <path> --json\`.
- CI should run \`prodocs check\` to reject stale generated documentation.

Generated at ${graph.generatedAt}.
`;
}

function renderCodeMap(graph, config) {
  const rows = graph.nodes
    .map((node) => {
      const symbols = node.symbols
        .slice(0, 8)
        .map((symbol) => `${symbol.name} (${symbol.kind}, L${symbol.line})`)
        .join("<br>");
      return `| [\`${escapeCell(node.path)}\`](${sourceLink(config.output, node.path)}) | ${node.language} | ${node.lines} | ${escapeCell(node.owner)} | ${symbols || "—"} |`;
    })
    .join("\n");

  return `${GENERATED_NOTICE}

# Code map

Every row is derived from the current source tree. Line references are evidence,
not prose claims.

| File | Language | Lines | Owner | Indexed symbols |
| --- | --- | ---: | --- | --- |
${rows}
`;
}

export async function writeArtifacts(root, config, graph) {
  const outputDirectory = await resolveOutputPath(root, config.output);
  await fs.mkdir(outputDirectory, { recursive: true });
  const [realRoot, realOutput] = await Promise.all([
    fs.realpath(root),
    fs.realpath(outputDirectory)
  ]);
  const outputStat = await fs.lstat(outputDirectory);
  if (outputStat.isSymbolicLink() || !isInside(realRoot, realOutput)) {
    throw new Error(
      `Refusing to write through an output path outside the project root: ${config.output}`
    );
  }

  const artifacts = [
    ["SYSTEM_OVERVIEW.md", renderSystemOverview(graph, config)],
    ["CODE_MAP.md", renderCodeMap(graph, config)],
    ["knowledge.json", `${JSON.stringify(graph, null, 2)}\n`],
    [
      "manifest.json",
      `${JSON.stringify(
        {
          schemaVersion: 1,
          sourceHash: graph.sourceHash,
          inputHash: graph.inputHash,
          generatedAt: graph.generatedAt,
          stats: graph.stats
        },
        null,
        2
      )}\n`
    ]
  ];

  await Promise.all(
    artifacts.map(([name, contents]) =>
      atomicWriteFile(path.join(outputDirectory, name), contents)
    )
  );

  return artifacts.map(([name]) => path.join(outputDirectory, name));
}
